version: "3"

services: 
    # PHP
    php:
        build: 
            context: ./php
            args: 
                APP_ENV: ${APP_ENV}
                PHP_VERSION: ${PHP_VERSION}
                REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}
        container_name: php
        restart: unless-stopped
        volumes: 
            - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
            - ./php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        env_file: .env
        ports: 
            - 9001:9001
        networks: 
            - lemp-network
    
    # NGINX
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes: 
            - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/nginx/ssl:/etc/nginx/ssl
        ports: 
            - 80:80
            - 443:443
        depends_on: 
            - php
        networks: 
            - lemp-network

    # MARIADB
    mariadb:
        image: mariadb:10.4.6
        command: --max_allowed_packet=32505856 
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
        volumes:
            - mariadb-data:/var/lib/mysql
        ports:
            - 3306:3306
        depends_on: 
            - php
        networks: 
            - lemp-network

# Docker Volumes for "LEMP"
volumes:
    mariadb-data:

# Docker Networks for "LEMP"
networks: 
    lemp-network:
        driver: bridge
